apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: add-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: add
        tier: backend
        track: stable
    spec:
      containers:
      - name: add
        image: "gcr.io/firsttry-178217/try-go-kit/services/add:latest"
        imagePullPolicy: Always
