apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer
