apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
        track: stable
    spec:
      containers:
      - name: gateway
        image: "gcr.io/firsttry-178217/try-go-kit/gateway:latest"
        imagePullPolicy: Always