apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: string-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: string
        tier: backend
        track: stable
    spec:
      containers:
      - name: string
        image: "gcr.io/firsttry-178217/try-go-kit/services/string:latest"
        imagePullPolicy: Always